Updates for AWS Exporter
asserts/helm-charts pull request #116
Opened 2023-07-21 14:38 UTC by jradhakrishnan

[ch16008]

2023-07-25 16:03 UTC, arramos84 commented
is this assuming the node already has the role to scrape? What happens if someone sets to true? Is this ready to go with true set? Just want to make sure if it's officially release that it's supported. Comment above the `awsExporterEnabled` flag would be good. Maybe a link to our docs or some description as to how to use it.

2023-07-26 03:01 UTC, jradhakrishnan commented
> is this assuming the node already has the role to scrape? What happens if someone sets to true? Is this ready to go with true set? Just want to make sure if it's officially release that it's supported. Comment above the `awsExporterEnabled` flag would be good. Maybe a link to our docs or some description as to how to use it.

This doesn't automatically trigger any of the AWS calls. One needs to add the AWS Account in the UI with the correct role. We have a documentation on how to add an account. The documentation needs to mention that `asserts-server` should be running with a role, and point the link to the CF template to create an account specific role with trust relationship with the source role.

2023-07-26 11:40 UTC, arramos84 approved these changes

2023-07-27 16:56 UTC, arramos84 commented on charts/asserts/Chart.yaml
> +version: 1.48.0
this version needs to be `1.49.0` now since we've merged another change.

2023-07-27 16:56 UTC, arramos84 requested changes
change version to `1.49.0`

2023-07-28 06:33 UTC, jradhakrishnan commented
> change version to `1.49.0`

Done

2023-07-28 11:33 UTC, arramos84 approved these changes

2023-07-28 12:43 UTC, merged